language: node_js
node_js:
  - 0.8
  - 0.6
  - 0.4
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.25.0.jar"
  - "java -jar selenium-server-standalone-2.25.0.jar -p 4444 > /dev/null 2>&1 &"
  - "cd node_modules/yahoo-arrow; npm install yui; cd ../..;"
  - "sleep 5"
script: "./bin/mojito jslint -p && ./tests/run.js test -u --group server --driver nodejs && ./tests/run.js test -u --group client --driver selenium && ./tests/run.js test -f"
notifications:
  email:
    recipients:
      - "devel-mojito@yahoo-inc.com"
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.freenode.org#mojito"
    on_success: change
    on_failure: always