language: node_js
node_js:
  - 0.8
  - 0.6
  - 0.4
branches:
  only:
    - master
    - develop
notifications:
  email: "devel-mojito@yahoo-inc.com"
    on_success: change
    on_failure: always
  irc: "irc.freenode.org#mojito"
    on_success: change
    on_failure: always